---
apiVersion: nb.mojaloop.io/v1alpha1
kind: NetbirdEnvConfig
metadata:
  name: netbird-env-config
  namespace: test
spec:
  parameters:
    pushSecret:
      esoPushSecret: false
    envProperties:
      setupKey:
        name: test-k8s-nodes-key
        namespace: test
        vaultSecretPath: test/netbird_k8s_setup_key
      groupNames:
        ccNetworkResource: cc-internal
        scNetworkResource: sc-internal
        envK8sNodes: test-k8s-nodes
    managedService:
      enabled: false
      setupKey:
        name: test-ms-gw-key
        namespace: test
        vaultSecretPath: test/netbird_ms_gw_setup_key
      groupNames:
        managedSvc: test-ms-gw
  providerConfigsRef:
    netbirdProviderConfigName: "netbird-crossplane-provider-config"
    k8sProviderConfigName: "kubernetes-provider"
  managementPolicies:
    - "*"
